<?php
/**
 * Working sample code to accompany the library. The instructions here assume
 * you've just cloned the repo. If you've installed via composer, you will want
 * to adjust the path to the autoloader.
 *
 * 1. Run the server. For example, under Linux you can probably use:
 * /usr/bin/php -S "localhost:8000" "examples/example-captcha.php"
 * 2. Point your browser at http://localhost:8000
 * 3. Follow the instructions
 *
 * @copyright Copyright (c) 2015, Google Inc.
 * @link      http://www.google.com/recaptcha
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once 'autoload.php';

include 'secrets.php';

// Register API keys at https://www.google.com/recaptcha/admin
// $siteKey = 'REPLACE_WITH_YOUR_KEYS'; // Variables assigned in secrets.php 
// $secret = 'REPLACE_WITH_YOUR_KEYS'; // Variables assigned in secrets.php 

// reCAPTCHA supported 40+ languages listed here: https://developers.google.com/recaptcha/docs/language

$lang = 'en';
?>